services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
      - "8081:8081"

  testing-container:
    build:
      context: ./tester
      dockerfile: Dockerfile.test
    command: tail -f /dev/null  # Keeps the container running
    depends_on:
      - nginx
