services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
      - "8081:8081"

  tester:
    build:
      context: ./tester
      dockerfile: Dockerfile.test
    depends_on:
      - nginx
