services:
  nginx:
    build:
      context: .
      dockerfile: nginx-docker-homeassignment/nginx/Dockerfile.nginx
    ports:
      - "8080:8080"
      - "8081:8081"

  tester:
    build:
      context: .
      dockerfile: nginx-docker-homeassignment/tester/Dockerfile.test
    depends_on:
      - nginx
