services:
  nginx:
    build:
      context: ./nginx-docker-homeassignment
      dockerfile: nginx/Dockerfile.nginx
    ports:
      - "8080:8080"
      - "8081:8081"

  tester:
    build:
      context: ./nginx-docker-homeassignment
      dockerfile: tester/Dockerfile.test
    depends_on:
      - nginx
