# Ubuntu as the base image
FROM ubuntu:latest

# Install Nginx
RUN apt-get update && apt-get install -y nginx && apt-get clean

# Copy Nginx configuration file into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the ports that the Nginx servers will listen on
EXPOSE 8080 8081

# Start Nginx in the foreground to keep the container running
CMD ["nginx", "-g", "daemon off;"]